"""add password hash

Revision ID: 867f24728d4e
Revises: c70d77f1cb7d
Create Date: 2026-05-26 13:20:39.381383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '867f24728d4e'
down_revision: Union[str, None] = 'c70d77f1cb7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_accounts', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_accounts', type_='unique')#type:ignore
    # ### end Alembic commands ###
